# Keep MediaSession / FGS entry points for host R8 / Play release builds.
-keep class expo.modules.dailyreactnativeplayer.PlaybackService { *; }
-keep class expo.modules.dailyreactnativeplayer.SpeechEngine { *; }
-keep class expo.modules.dailyreactnativeplayer.SessionHolder { *; }
-keep class expo.modules.dailyreactnativeplayer.ArtworkLoader { *; }
-keep class expo.modules.dailyreactnativeplayer.RemoteEventHub { *; }
-keep class expo.modules.dailyreactnativeplayer.HeadlessPlaybackBootstrap { *; }
-keep class androidx.media3.session.MediaSessionService { *; }
-keep class androidx.media3.session.MediaSession { *; }
-keep class androidx.media3.session.MediaSession$Builder { *; }
-keep class androidx.media3.session.MediaSession$ControllerInfo { *; }
-keep class androidx.media3.session.MediaSession$Callback { *; }
-keep class androidx.media3.session.DefaultMediaNotificationProvider { *; }
-keep class androidx.media3.session.DefaultMediaNotificationProvider$Builder { *; }
-keep class androidx.media3.common.ForwardingPlayer { *; }
